version: "3.8"

services:
  api1:
    build: .
    container_name: api1
    env_file:
      - .env
    depends_on:
      - mongo
      - kafka

  api2:
    build: .
    container_name: api2
    env_file:
      - .env
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

  nginx:
    build: ./nginx
    container_name: nginx_lb
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2

  # SIMPLE KAFKA (no zookeeper needed)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'false'  # Disable zookeeper
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"

  mailer:
    build: ./mailer
    container_name: mailer
    env_file:
      - .env
    depends_on:
      - kafka
      - mongo

volumes:
  mongo_data:
