openapi: 3.0.3
info:
  title: Retro Video Game Exchange API
  description: REST API for trading retro video games (RMM Level 3 - HATEOAS)
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        status:
          type: integer

    Link:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
        method:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        streetAddress:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'

    UserUpdate:
      type: object
      properties:
        name:
          type: string
        streetAddress:
          type: string

    Game:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        publisher:
          type: string
        yearPublished:
          type: integer
        system:
          type: string
        condition:
          type: string
          enum: [mint, good, fair, poor]
        previousOwners:
          type: integer
        ownerId:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'

    GameCreate:
      type: object
      required:
        - name
        - publisher
        - yearPublished
        - system
        - condition
      properties:
        name:
          type: string
        publisher:
          type: string
        yearPublished:
          type: integer
        system:
          type: string
        condition:
          type: string
          enum: [mint, good, fair, poor]
        previousOwners:
          type: integer

    GameUpdate:
      type: object
      properties:
        name:
          type: string
        publisher:
          type: string
        yearPublished:
          type: integer
        system:
          type: string
        condition:
          type: string
          enum: [mint, good, fair, poor]
        previousOwners:
          type: integer

paths:

  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [name, email, password, streetAddress]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                streetAddress:
                  type: string
      responses:
        201:
          description: User created
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: Authenticate user
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: JWT returned
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
        401:
          description: Invalid credentials

  /users/me:
    get:
      summary: Get authenticated user
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        200:
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Unauthorized

    put:
      summary: Update authenticated user (name & address only)
      tags: [Users]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        200:
          description: User updated
        400:
          description: Invalid update
        401:
          description: Unauthorized

  /users/{id}/games:
    get:
      summary: Get all games owned by a specific user
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of user's games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        404:
          description: User not found

  /games:
    get:
      summary: Search games
      tags: [Games]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: system
          schema:
            type: string
      responses:
        200:
          description: List of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'

    post:
      summary: Create a game listing
      tags: [Games]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameCreate'
      responses:
        201:
          description: Game created
        400:
          description: Invalid input
        401:
          description: Unauthorized

  /games/{id}:
    get:
      summary: Get game details
      tags: [Games]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Game details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        404:
          description: Game not found

    put:
      summary: Update a game (owner only)
      tags: [Games]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameUpdate'
      responses:
        200:
          description: Game updated
        401:
          description: Unauthorized
        403:
          description: Not game owner
        404:
          description: Game not found

    delete:
      summary: Delete a game (owner only)
      tags: [Games]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Game deleted
        401:
          description: Unauthorized
        403:
          description: Not game owner
        404:
          description: Game not found
